export enum NODE_ENVIRONMENTS {
  DEVELOPMENT = 'development',
  TEST = 'test',
  PRODUCTION = 'production'
}

export enum DEPLOY_STAGES {
  LOCAL = 'LOCAL',
  DEV = 'DEV',
  PROD = 'PROD',
  TEST = 'TEST',
  E2E = 'E2E'
}

export enum CONFIG_KEYS {
  MONGO_URL = 'MONGO_URL',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRATION_SECONDS = 'JWT_EXPIRATION_SECONDS',
  PASSWORD_SALT_ROUNDS = 'PASSWORD_SALT_ROUNDS',
  RECAPTCHA_KEY = 'RECAPTCHA_KEY',
  NODE_ENV = 'NODE_ENV',
  STAGE = 'STAGE',
  S3_BUCKET = 'S3_BUCKET',
  COOKIE_DOMAIN = 'COOKIE_DOMAIN',
  COOKIE_NAME = 'COOKIE_NAME'
}

export enum COLLECTIONS {
  USERS = 'users'
}
