# main user model
type User {
    id: String!
    username: String!
    firstName: String
    lastName: String
    email: String!
    password: String!
    createDate: String!
}

# common for multiple user transactions
input UserPartial {
    username: String
    firstName: String
    lastName: String
    email: String
    password: String
}
input UserRequest {
    user: UserPartial!
}

# createUser
type CreateUserResponse {
    user: User!
    jwt: String!
}

############## QUERIES and MUTATIONS #############
type Query {
    getUser(input: UserRequest!): User
}
type Mutation {
    createUser(input: UserRequest!): CreateUserResponse
}
